FROM golang:alpine:3 as builder

WORKDIR $GOPATH/src/github.com/owenthereal/upterm
COPY . .
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go install ./cmd/uptermd/...

# Prepare for image
FROM python:3.9.16-alpine

LABEL org.opencontainers.image.source https://github.com/owenthereal/upterm

RUN adduser -D uptermd
USER uptermd

WORKDIR /app
ENV PATH="/app:${PATH}"

COPY --from=builder /go/bin/* /app

# sshd
EXPOSE 2222
# ws
EXPOSE 8080
# Prometheus
EXPOSE 9090

ENTRYPOINT ["uptermd"]
