name: install

on:
  push: 
    branches: ['test']
  repository_dispatch:
  pull_request:
    branches : ['master']


jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - uses: marcofranssen/setup-kubectl@v0.3.0
              with:
                enable-plugins: true
            - run: echo ${{ steps.kubectl.output.krew-version }}
            - run: kubectl krew install aws-auth
            - uses: alexellis/setup-arkade@v1
            - uses: alexellis/arkade-get@master
              with:
                kubectl: latest
                kustomize: latest
                kubeconform: latest
                helm: latest
                jq: latest
                yq: latest
            - name: run test
              run: |
                kubectl version --client
                kustomize version
                kubeconform -v
                helm version
                jq --version
                yq --version
                git --version
                git remote -v

