name: install

on:
  push: 
    branches: ['test']
  repository_dispatch:
  pull_request:
    branches : ['master']


jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install krew
              uses: developer-guy/setup-krew@main
              with:
                krew-version: 'v0.4.2'
            - name: Check install!
              run: krew version

            - uses: alexellis/setup-arkade@v1
            - uses: alexellis/arkade-get@master
              with:
                kubectl: latest
                kustomize: latest
                kubeconform: latest
                helm: latest
                jq: latest
                yq: latest

            - name: run test
              run: |
                kubectl version --client
                kustomize version
                kubeconform -v
                helm version
                jq --version
                yq --version
                git --version
                git remote -v
                kubectl krew
