name: install

on:
  push: 
    branches: ['master']
  repository_dispatch:
  pull_request:


jobs:
    install-arkade:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - run: |
                ls
                
            - uses: alexellis/setup-arkade@v1
            - uses: alexellis/arkade-get@master
              with:
                kubectl: latest
                kustomize: latest
                kubeconform: latest
                helm: latest
                jq: latest
                yq: latest
            - run: |
                kubectl version --client
                kustomize version
                kubeconform -v
                helm version
                jq --version
                yq --version
                ls -la