name: install

on:
  push: 
    branches: ['master']
  repository_dispatch:
  pull_request:
    branches : ['master']


jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: install krew binary
              uses: giantswarm/install-binary-action@VERSION
              with:
                binary: "krew-darwin_amd64"
                version: "v.4.3"
                download_url: "https://github.com/kubernetes-sigs/krew/releases/download/${version}/${binary}.tar.gz"
                tarball_binary_path: "*/src/${binary}"
                # smoke_test: "${binddary} --version"             
            - uses: alexellis/setup-arkade@v1
            - uses: alexellis/arkade-get@master
              with:
                kubectl: latest
                kustomize: latest
                kubeconform: latest
                helm: latest
                jq: latest
                yq: latest
            - name: run test
              run: |
                kubectl version --client
                kustomize version
                kubeconform -v
                helm version
                jq --version
                yq --version
                git --version
                git remote -v
                ls $HOME
