name: Build

on:
  push: 
    branches: ['master']
  repository_dispatch:
  pull_request:

jobs:
  build-and-test:  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
      - name: build and test
        run: |
          # Build image follow by Makefile.docker_build
          make docker_build
          # Test image
          docker run -it uptermd:latest
  # build:
  #   name: Compile
  #   runs-on: ${{ matrix.os  }}
  #   strategy:
  #     matrix:
  #       os: [ macos-latest, ubuntu-latest,  ]
  #   steps:
  #   - name: Set up Go 1.x
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: ^1.19
  #     id: go
  #   - name: Check out code into the Go module directory
  #     uses: actions/checkout@v2
  #   - name: Compile
  #     run: make install
  # test:
  #   name: Test
  #   runs-on: ${{ matrix.os  }}
  #   strategy:
  #     matrix:
  #       os: [ macos-latest, ubuntu-latest,  ]
  #   steps:
  #   - name: Set up Go 1.x
  #     uses: actions/setup-go@v2
  #     with:
  #       go-version: ^1.19
  #     id: go
  #   - name: Check out code into the Go module directory
  #     uses: actions/checkout@v2
  #   - name: Test
  #     run: make test
  #     env:
  #       BASH_SILENCE_DEPRECATION_WARNING: 1 # See https://www.loekvandenouweland.com/content/the-default-interactive-shell-is-now-zsh.html
  #       MUTE_FLAKY_TESTS: 1
  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Vet
      run: make vet
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Docker
      run: make docker_build
