name: install

on:
  push: 
    branches: ['master']
  repository_dispatch:
  pull_request:
    branches : ['master']


jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: install krew
              uses: marcofranssen/setup-kubectl@v0.3.0
              with:
                enablePlugins: true
            - run: echo ${{ steps.kubectl.output.krew-version }}
            - run: kubectl krew install aws-auth

            - uses: alexellis/setup-arkade@v1
            - uses: alexellis/arkade-get@master
              with:
                kubectl: latest
                kustomize: latest
                kubeconform: latest
                helm: latest
                jq: latest
                yq: latest
            - name: run test
              run: |
                kubectl version --client
                kustomize version
                kubeconform -v
                helm version
                jq --version
                yq --version
                kubectl krew
                /kind create cluster
