name: Release
on:
  push:
    tags: 'v*'
jobs:
  release:
    name: Upload releases
    runs-on: ubuntu-latest
    if: '!contains(github.ref, "-")' # skip prereleases
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Docker push on master
        run: |
          # Build & publish on master
          echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin
          TAG=${GITHUB_REF_NAME} make docker_push
          TAG=latest make docker_push
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
